name: test_client

on: 
  - workflow_dispatch  # Disable running on every commit because this job downloaded a 4gb image and github actions have no cache

jobs:

  test_client:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: make test_client
        run: make test_client

      - name: upload-artifact test reports
        uses: actions/upload-artifact@v3
        with:
            name: cypress
            path: test_client/reports/
            retention-days: 5
